# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ced6b23f641dc984ffb9a122e48cfcc746c9929a26465f81720ee777de2bd61673d5416423253c786ca8117a555f484b1e4a3bfe42c4aeed1d4cae7fe04b5cde

test:
  secret_key_base: 7ecbf73e7efdeb9f5bb0e5a20bacddd6ed03795d6617b924bb597da0239fdb44633c40c25a054b5e27a2c52a3da9c3711e3a1113789f12ee4a9063922cb916ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
